name = "bureauweb-ca"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Variables d'environnement
[vars]
NEXT_PUBLIC_CONTACT_PHONE = "5145340837"
NEXT_PUBLIC_HIDE_HEADER_PHONE = true
